server.port=8081
server.servlet.context-path=/api/v1

logging.level.root=info

#Resilience4j RateLimiter
resilience4j.ratelimiter.instances.public-api.limit-for-period=5
resilience4j.ratelimiter.instances.public-api.limit-refresh-period=60s
resilience4j.ratelimiter.instances.public-api.timeout-duration=0s
#Resilience4j RateLimiter

#SpringProperties
spring.application.name=aplazo-online-shopping-system
#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aplazo_shopping_system_db
spring.datasource.username=postgres
spring.datasource.password=123456
#PostgreSQL
#SpringJPA
spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#SpringJPA
spring.sql.init.data-locations=classpath:/sql/credit-line-rule-data.sql,classpath:/sql/payment-scheme-data.sql
spring.sql.init.mode=never
#SpringProperties